Feature/recaptcha
CHI-internship/main-frontend pull request #13
Opened 2022-11-10 20:26 UTC by TanyaDovzhenko

2022-11-11 09:00 UTC, RamboUA approved these changes

2022-11-11 09:00 UTC, RamboUA commented on src/components/auth/recover-password-form.tsx
> +import { useGoogleReCaptcha } from "react-google-recaptcha-v3";
Better to import libs on the very top

2022-11-17 15:58 UTC, BillyAleks requested changes

2022-11-17 15:58 UTC, BillyAleks commented on src/utils/recaptcha.ts
> +    if (executeRecaptcha) return await executeRecaptcha('action')
for what do we need await here?

2022-11-22 07:06 UTC, BillyAleks reviewed
Thanks, please check the comments

2022-11-29 08:04 UTC, RamboUA requested changes
Thanks, please check the comment

2022-11-29 08:04 UTC, RamboUA commented on src/components/auth/sign-in-form.tsx
> +        {isError ? (
```suggestion
        {isError && <Alert severity='error'>Wrong email or password</Alert>}
```

2022-11-29 08:04 UTC, RamboUA commented on src/components/auth/sign-in-form.tsx
> +          {({ errors, touched, isValid, dirty }) => {
```suggestion
          {({ errors, touched, isValid, dirty }) => (
              <Form
                style={{
                  display: 'flex',
                  ...
```

2022-11-29 08:04 UTC, RamboUA commented on src/pages/auth/reset-password.tsx
> +import { useGoogleReCaptcha } from 'react-google-recaptcha-v3'
Maybe we could add a rule of imports. It looks better when libs are imported on a top level

2022-11-29 08:04 UTC, RamboUA commented on src/pages/auth/reset-password.tsx
>      onSubmit: async (values) => {
Better to do it as a separate function

2022-11-29 14:29 UTC, merged