feature/orders
CHI-internship/main-frontend pull request #14
Opened 2022-11-14 15:47 UTC by TanyaDovzhenko

2022-11-15 06:49 UTC, BillyAleks requested changes

2022-11-15 06:49 UTC, BillyAleks commented on src/components/orders/OrderCard.tsx
> +    ({ order }: IOrderCardProps) => {
after you mentioned FC<IOrderCardProps> there no need to specify a variable type of order it will be settled automatically

2022-11-15 06:49 UTC, BillyAleks commented on src/pages/orders/Orders.tsx
> +            {orders.map((item: any) => <OrderCard key={item.id} order={item} />)}
shouldn't item has an IOrder type?

2022-11-16 09:23 UTC, lerik1408 reviewed
GJ!

2022-11-16 09:46 UTC, merged