add default header
CHI-internship/main-frontend pull request #2
Opened 2022-10-31 12:16 UTC by TMysiv

create header

2022-11-01 09:16 UTC, lerik1408 approved these changes

2022-11-03 09:20 UTC, BillyAleks requested changes
Thank you. Please check out comments

2022-11-03 09:20 UTC, BillyAleks commented on src/components/Header.tsx
> +import React, { FC } from 'react';
you don't need to import React after v17

2022-11-03 09:20 UTC, BillyAleks commented on src/components/Header.tsx
> +            sx={{ flexGrow: 1 }}>
Better to put closing brace on a next line

2022-11-03 09:20 UTC, BillyAleks commented on src/components/Header.tsx
> +                src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4OPBibmFcA0jgIPbN-6wPiy37vbmfQN7SAg&usqp=CAU'
Better to upload an default image, like anonymous avatar.
https://www.freepik.com/free-photos-vectors/default-avatar

2022-11-03 09:20 UTC, BillyAleks commented on src/components/Header.tsx
> +const Header: FC = () => {
if you do not have any logic, inside a function, only render - return directly JSX

2022-11-03 09:20 UTC, BillyAleks commented on src/components/Header.tsx
> +    <>
Is there any reason to use fragment here?

2022-11-03 11:47 UTC, TMysiv commented on src/components/Header.tsx
> +import React, { FC } from 'react';
fixed

2022-11-03 11:47 UTC, TMysiv commented on src/components/Header.tsx
> +            sx={{ flexGrow: 1 }}>
fixed

2022-11-03 11:47 UTC, TMysiv commented on src/components/Header.tsx
> +                src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4OPBibmFcA0jgIPbN-6wPiy37vbmfQN7SAg&usqp=CAU'
done

2022-11-03 11:47 UTC, TMysiv commented on src/components/Header.tsx
> +const Header: FC = () => {
fixed

2022-11-03 11:47 UTC, TMysiv commented on src/components/Header.tsx
> +    <>
fixed

2022-11-03 13:35 UTC, RamboUA approved these changes

2022-11-03 13:39 UTC, merged