Feature/activate volunteer
CHI-internship/main-frontend pull request #24
Opened 2022-11-21 18:51 UTC by pavlokolodka

https://trello.com/c/yVisM7lo

2022-11-22 07:44 UTC, BillyAleks requested changes
Thanks, please check comments.
I would recommend not to use a blank lines in JSX. It makes it a little bit harder to see the hierarchy.

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/Profile.tsx
> +    const getUser = async () => {
Better to move out function from useEffect and just invoke it inside

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +
To many blank lines. Normally you should use 1 and just sometimes in rare cases you can use 2 maximum.
It's not a rule in general, but 90% of code base is written in such a behavior

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +const toBase64 = async (file: Blob): Promise<string> => await new Promise((resolve, reject) => {
I would move this function to global helpers, as this function can be useful not only for this component.

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +    async function getUser(token: string | null) {
same about function. Leave only invoking in here

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +        Activate Profile
Indent is missing

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +          {({ values, errors, touched, isValid, dirty, setFieldValue }) => {
You can return directly JSX here

2022-11-22 07:44 UTC, BillyAleks commented on src/components/profile/profile-activate/ProfileActivate.tsx
> +                    setFieldValue('expansion', type);
I don't like here that it's potentially two same setFieldValue will trigger re-rendering twice. Is it possible to refactor it to set this value only once?

2022-11-22 07:44 UTC, BillyAleks commented on src/pages/profile/profile-activate-page.tsx
> +    const getUser = async () => {
It looks like you have used this function before. What do you think of making it more global and reusable?

2022-11-22 07:44 UTC, BillyAleks commented on src/pages/profile/profile-activate-page.tsx
> +  return (
```suggestion
if (!user) return null;
return <ProfileUpdate />;
```

2022-11-22 10:56 UTC, pavlokolodka commented
Merge with https://github.com/CHI-internship/KraudDonate-Service/pull/36

2022-11-25 09:15 UTC, lerik1408 approved these changes

2022-11-25 10:19 UTC, merged