Feature/create order
CHI-internship/main-frontend pull request #25
Opened 2022-11-21 22:26 UTC by TanyaDovzhenko

2022-11-22 07:58 UTC, BillyAleks requested changes

2022-11-22 07:58 UTC, BillyAleks commented on src/api/orders.service.ts
> +    return await axiosInstance.post('orders', orderDto)
I think this await is useless, as you are not storing result and chain catch statement directly to Promise.

2022-11-22 07:58 UTC, BillyAleks commented on src/components/profile/profile-avatar/ProfileAvatar.tsx
> +        if (image) await userService.updatePofile({ userId, image })
I think here is also not necessary to use await. handleUpload function returns promise

2022-11-22 07:58 UTC, BillyAleks commented on src/pages/order/CreateOrder/CreateOrder.tsx
> +                        setTimeout(() => setSuccess(false), 3000)
Timeouts is better to store in Refs, because if you unmount component earlier than the timer will fire a callback - you'll have a huge warning in a browser console

2022-11-22 07:58 UTC, BillyAleks commented on src/utils/base64.ts
> +  }).then(data => { return data }).catch(() => { return '' })
```suggestion
  })
  .then(data =>  data)
  .catch(() => '')
```

2022-11-22 07:58 UTC, BillyAleks commented on src/utils/base64.ts
> +  return await stringBase64
no need for await

2022-11-22 07:59 UTC, BillyAleks commented
Please do not use **any** as a type, it makes usage of a TypeScript - useless

2022-11-25 13:30 UTC, lerik1408 approved these changes
GJ

2022-11-25 13:32 UTC, merged