Add sign in sign up pages
CHI-internship/main-frontend pull request #3
Opened 2022-10-31 13:20 UTC by nottoday2471

Was created authorization form with link to sign up and recover password
![image](https://user-images.githubusercontent.com/72010868/199016733-3a3cabef-57a9-48c2-8bc3-6799986bb069.png)
Was created sign up form 
![image](https://user-images.githubusercontent.com/72010868/199016999-3e212cec-6e97-4692-a53a-b2226342ce26.png)
Was created recover password form
![image](https://user-images.githubusercontent.com/72010868/199017064-f3a37f40-baa6-47a4-ad24-6bf91eb9148b.png)
Also was added validation for email and password
![image](https://user-images.githubusercontent.com/72010868/199017211-7e16c9d3-46fa-4f56-8f07-c52d192f923d.png)
![image](https://user-images.githubusercontent.com/72010868/199017303-0d9b7d6a-2562-430c-93eb-714dad90d13e.png)
![image](https://user-images.githubusercontent.com/72010868/199017374-58d65cbe-8297-4bcb-bf4a-1a92ce9f3761.png)

2022-11-02 20:11 UTC, lerik1408 approved these changes
Good job!

2022-11-02 20:11 UTC, lerik1408 commented on src/utils/valdiate-password.ts
> +};
I think a better way is to have one file sharedValidate, for validating shared fields like email, password, uuid.

2022-11-03 09:14 UTC, BillyAleks requested changes
Thank you, please check the comments and apply it to all changes that you've done.
I would recommend to use you Yup and Formik to handle and validate forms.
Check autotypes, not everywhere you need an explicit definition.

2022-11-03 09:14 UTC, BillyAleks commented on src/utils/validate-email.ts
> +export const validateEmail = (email: string): boolean => {
Yup lib have email validator as well, so you could use it

2022-11-04 17:17 UTC, merged