Fix/profile_user_context
CHI-internship/main-frontend pull request #30
Opened 2022-11-26 22:35 UTC by TanyaDovzhenko

2022-11-28 12:29 UTC, RamboUA requested changes
Thank you, good job. Please check the comments.
Also check your changes if you have some blank lines in JSX (consider adding it as a eslint rule).
Check handlers in props of component. It's always better to create handler function outside and pass it in props, except some really simple and compact callbacks.

2022-11-28 12:29 UTC, RamboUA commented on src/components/common/header/HeaderInfo.tsx
> +        <div> {user ?
As it is a separate div in a result - better to write it from a new line

2022-11-28 12:29 UTC, RamboUA commented on src/components/common/header/HeaderInfo.tsx
> +                    onClick={() => { localStorage.removeItem('token'); navigate('/sign-up') }}
Please put this handler to a function outside JSX.

2022-11-28 12:29 UTC, RamboUA commented on src/components/profile/profile-activate/ProfileActivate.tsx
>                    onChange={(event) => {
This handler should be outside as well

2022-11-28 20:20 UTC, TanyaDovzhenko commented on src/components/profile/profile-activate/ProfileActivate.tsx
>                    onChange={(event) => {
> This handler should be outside as well

this callback is inside the formic field "{({ errors, touched, isValid, dirty, setFieldValue }) => {" and uses the setFieldValue method, so if it is moved to a separate function, the setFieldValue method will be unavailable

2022-11-29 08:25 UTC, RamboUA requested changes
Thank you, great, just check please other comments. And one answer to your argument.

2022-11-29 08:25 UTC, RamboUA commented on src/components/auth/sign-in-form.tsx
> +    await userService
Probably it's possible to avoid await here as well

2022-11-29 08:25 UTC, RamboUA commented on src/components/auth/sign-up-form.tsx
> +          onSubmit={async (values, formikHelpers) => {
I'd recommend to move it outside from JSX

2022-11-29 08:25 UTC, RamboUA commented on src/components/common/header/HeaderInfo.tsx
> +            {user ? <div>
indents are wrong, I would recommend to follow structure:
```
{user ?
   (
      <div>
         ...
      </div>
   ) : (
      <div>
         ...
      </div>
   )
}

```

2022-11-29 08:25 UTC, RamboUA commented on src/components/orders/UpdateOrder/UpdateOrder.tsx
> +  const [error, setError] = useState<string>('');
I think it's not necessary to use typing, it should set automatically, when you define error in state as an empty string.
```suggestion
  const [error, setError] = useState('');
```

2022-11-29 08:25 UTC, RamboUA commented on src/components/orders/UpdateOrder/UpdateOrder.tsx
> +  const onSubmit = async (values: FormikValues, formikHelpers: any) => {
Can we try to get rid of any here, please?

2022-11-29 08:25 UTC, RamboUA commented on src/components/orders/UpdateOrder/UpdateOrder.tsx
> +    } catch (e: any) {
and here

2022-11-29 08:25 UTC, RamboUA commented on src/components/orders/UpdateOrder/UpdateOrder.tsx
> +        {({ errors, touched, isValid, dirty, setFieldValue }) => {
```suggestion
        {({ errors, touched, isValid, dirty, setFieldValue }) => (
           <Form className={styles.form}>
           ...
```

2022-11-29 08:25 UTC, RamboUA commented on src/components/profile/profile-activate/ProfileActivate.tsx
>                    onChange={(event) => {
I would not agree with you. You can always pass it as an argument to external function.

2022-11-29 13:44 UTC, BillyAleks approved these changes

2022-11-29 13:49 UTC, merged