Feature/stripe_payment
CHI-internship/main-frontend pull request #33
Opened 2022-11-30 09:55 UTC by TanyaDovzhenko

2022-12-01 09:44 UTC, RamboUA requested changes
Great job, please, check the comments below

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/OrderDetails/OrderDetails.module.scss
> +.infoItem,
Can we use same naming convention? let's use just snake or just camel.

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/OrderDetails/OrderDetails.tsx
> +            <ProgressBar moneyHave={order?.sum} moneyNeed={order?.goal_amount}
```suggestion
            <ProgressBar
                moneyHave={order?.sum}
                moneyNeed={order?.goal_amount}
                closedAt={new Date(order?.finished_at)}
                size='large'
            />
```
will be more easy to use

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/OrderDetails/OrderDetails.tsx
> +                  {cn(style.status, { [style.gathering_open]: order?.status === 'open' })}>
Is it because of string length linter rule? Maybe we can use 140symb lenght then?
It should be in a single line

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/OrderDetails/OrderDetails.tsx
> +                    onChange={(e) => setCurrency(e.target.value as PaymentCurrency)}>
```suggestion
                    onChange={(e) => setCurrency(e.target.value as PaymentCurrency)}
               >
```

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/OrderDetails/OrderDetails.tsx
> +                    onChange={(e) => setCurrency(e.target.value as PaymentCurrency)}>
It's better, because you're able to see proper indents

2022-12-01 09:44 UTC, RamboUA commented on src/components/orders/UpdateOrder/UpdateOrder.tsx
>        } catch (err: any) {
Can we set it to unknown or leave without type at all?

2022-12-01 09:44 UTC, RamboUA commented on src/components/payment/CheckoutForm.tsx
> +            <Button sx={{ margin: '15px auto' }} type='submit'
same here
```suggestion
            <Button
                sx={{ margin: '15px auto' }}
                type='submit'
                variant='outlined'
                disabled={inProcess}
            >
```

2022-12-01 09:44 UTC, RamboUA commented on src/components/payment/Payment.tsx
> +    const [clientSecret, setClientSercet] = useState()
What type does it shows?

2022-12-01 09:44 UTC, RamboUA commented on src/components/payment/Payment.tsx
> +
```suggestion
   if (!stripePromise || !clientSecret) return null;
   
   return (
      <Elements stripe={stripePromise} options={{ clientSecret }}>
            <CheckoutForm />
        </Elements>
   );
```

2022-12-01 09:44 UTC, RamboUA commented on src/pages/payment/CompletedPayment.tsx
> +
remove extra blank line, please

2022-12-05 08:20 UTC, BillyAleks approved these changes

2022-12-05 09:48 UTC, merged