add logic for authorization with 2 tokens
CHI-internship/main-frontend pull request #36
Opened 2022-11-30 17:48 UTC by nottoday2471

2022-12-01 09:16 UTC, RamboUA requested changes
Great job, please check the comments below

2022-12-01 09:16 UTC, RamboUA commented on src/helpers/getNewAuthTokens.ts
> +  refreshToken: string | null,
```suggestion
  refreshToken?: string,
```

2022-12-01 09:16 UTC, RamboUA commented on src/helpers/getNewAuthTokens.ts
> +      console.log(err);
Is it something intended?
Better not to left console.logs if there no special need for it

2022-12-01 09:16 UTC, RamboUA commented on src/helpers/retrieveUser.ts
> +  // const rawUser = await userService
Do you still need this commented part? If so can you please add TODO: of what should be done with this commented code further?

2022-12-05 08:27 UTC, BillyAleks approved these changes

2022-12-05 12:51 UTC, merged