add volunteers hints
CHI-internship/main-frontend pull request #38
Opened 2022-12-03 19:22 UTC by TMysiv

2022-12-05 10:11 UTC, BillyAleks requested changes

2022-12-05 10:11 UTC, BillyAleks commented on src/pages/hint/hints/Hints.tsx
> +      <div className={style.container}>
I think here something wrong with indents. Can you please check

2022-12-05 10:11 UTC, BillyAleks commented on src/pages/hint/hints/Hints.tsx
> +      <div className={style.container}>
```suggestion
          <div className={style.container}>
```

2022-12-06 14:24 UTC, TMysiv commented on src/api/hint.service.ts
> +
fix

2022-12-06 14:25 UTC, TMysiv commented on src/pages/hint/hintSingle/Hint.tsx
> +    await hintService.getHintById(id).then(value => {
fix

2022-12-06 14:25 UTC, TMysiv commented on src/pages/hint/hintSingle/Hint.tsx
> +    <div>
fix

2022-12-06 14:27 UTC, TMysiv commented on src/pages/hint/hints/Hints.tsx
> +      <div className={style.container}>
fix

2022-12-06 14:27 UTC, TMysiv commented on src/pages/hint/hints/Hints.tsx
> +      <div className={style.container}>
fix

2022-12-07 16:08 UTC, lerik1408 reviewed
Fix the conflicting files

2022-12-07 21:33 UTC, merged