add pfofile page
CHI-internship/main-frontend pull request #4
Opened 2022-11-02 15:50 UTC by TanyaDovzhenko

2022-11-02 21:08 UTC, lerik1408 reviewed
Good Job!

2022-11-02 21:08 UTC, lerik1408 commented on src/api/user/update-profile.ts
> +  return updatedPhoto
https://github.com/CHI-internship/KraudDonate-Service/pull/4#pullrequestreview-1166008438 - first comment

2022-11-03 08:09 UTC, BillyAleks requested changes
Thank you. Please check comments.
Also would be great to add to each components folder index.ts file to make further imports shorter.

2022-11-03 08:09 UTC, BillyAleks commented on src/api/user/update-profile.ts
> +export async function updateProfileLastname(userId: number, lastname: string) {
I have a question for discussion. Why there are two user-update queries???
As for me it looks like it's better in a single query.
But this question is for backend.

2022-11-03 08:09 UTC, BillyAleks commented on src/components/profile/profile-avatar/ProfileAvatar.tsx
> +export default function ProfileAvatar({ userId, initialAvatar }: IProfileAvatarProps) {
it should have a type FC<IProfileAvatarProps>

2022-11-03 08:09 UTC, BillyAleks commented on src/components/profile/profile-avatar/ProfileAvatar.tsx
> +}
Please add default props here for component, using prop-types lib

2022-11-03 08:09 UTC, BillyAleks commented on src/components/profile/profile-avatar/ProfileAvatar.tsx
> +  initialAvatar: string | null
I think it's possible to use an optional prop here.

2022-11-03 08:09 UTC, BillyAleks commented on src/components/profile/profile-name/ProfileName.tsx
> +export default function ProfileName({ userId, initialName, initialLastname }: IProfileNameProps) {
same about component type

2022-11-04 09:19 UTC, lerik1408 commented on src/api/user/update-profile-name.ts
> +    `${process.env.REACT_APP_BASE_SERVICE_URL}user-update/name`,
👀

2022-11-04 09:19 UTC, lerik1408 commented on src/api/user/update-profile-name.ts
> +  const updatedName = await axios.put(
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});

2022-11-04 18:10 UTC, lerik1408 reviewed
GJ

2022-11-04 18:10 UTC, lerik1408 commented on src/api/user/update-profile.ts
> +  return updatedUser
👀

2022-11-07 08:59 UTC, lerik1408 reviewed
GJ

2022-11-07 09:00 UTC, lerik1408 commented on package.json
> +>>>>>>> main
Something with merge

2022-11-07 09:26 UTC, lerik1408 reviewed
GJ

2022-11-07 09:26 UTC, merged