add update hint component
CHI-internship/main-frontend pull request #44
Opened 2022-12-08 14:07 UTC by TMysiv

2022-12-09 08:16 UTC, RamboUA requested changes
Nice. Just consider please a couple of comments:

2022-12-09 08:16 UTC, RamboUA commented on src/components/hint/updateHint/UpdateHint.tsx
> +              callback={fileBase64 => {
Can we write it as a function outside a JSX?

2022-12-09 08:16 UTC, RamboUA commented on src/components/hint/updateHint/UpdateHint.tsx
> +    validationSchema: yup.object({
I would recommend to keep initial values and validation schema in a module nearby. You could call it something like config.js in updateHint folder

2022-12-11 12:36 UTC, TMysiv commented on src/components/hint/updateHint/UpdateHint.tsx
> +              callback={fileBase64 => {
fix

2022-12-11 12:58 UTC, TMysiv commented on src/components/hint/updateHint/UpdateHint.tsx
> +    validationSchema: yup.object({
fix

2022-12-12 06:57 UTC, RamboUA approved these changes
Good thank you

2022-12-12 08:36 UTC, merged