Query caching
CHI-internship/main-frontend pull request #48
Opened 2022-12-22 10:58 UTC by nottoday2471

2022-12-22 11:59 UTC, RamboUA requested changes
Great job. Just check a comment please

2022-12-22 11:59 UTC, RamboUA commented on src/pages/orders/Orders.tsx
> +  const { isLoading, data, error, isError } = useQuery<IOrder[], AxiosError>(
I think it is better to make as a hook, for being able to use it in multiple places

2022-12-23 09:09 UTC, BillyAleks reviewed
So approximate flow should be like this:
- You have hook, which just making a bind service for useQuery;
- Inside of this hook you use query getOrders;
- in Orders.tsx you get your { isLoading, data, error, isError }
- also here you should use useEffect to set pages count

2022-12-23 09:09 UTC, BillyAleks commented on src/hooks/orders.hook.ts
> +      const orders = await fn({
you could use here directly getOrders, as it should be the only possible query for this hook.

2022-12-23 09:09 UTC, BillyAleks commented on src/helpers/getOrders.ts
> +  setTotalPages(res.totalPages);
It's not really good idea to break single responsibility principle of function. Better to bring a result outside and set pages count on that level

2022-12-23 16:33 UTC, merged